/**
 * Blocks to source text.
 *
 * The generator walks each event's execution chain and emits ordinary
 * TypeScript. It is deterministic: the same graph produces the same text,
 * byte for byte, which is what makes the result safe to write into a file
 * the user also edits by hand, and what keeps diffs honest.
 *
 * Every emitted line remembers the block it came from. That map is what
 * turns `TypeError on line 42` into a highlighted block on the canvas, and
 * what lets the canvas reveal the code for a block the user selects.
 */

import { findPort, type BlockGraph, type BlockNode, type BlockRegistry } from './blockSchema'
import { incoming, nodeById, outgoing } from './graph'
import { generateState, type AppVariable } from './appState'

export const GENERATED_HEADER = '// Generated by the Tungsten builder. Edit the blocks or this file; they stay in step.'

export type SourceMapEntry = { line: number; nodeId: string }

export type GeneratedProgram = {
  code: string
  /** One entry per emitted statement, by 1-based line. */
  sourceMap: SourceMapEntry[]
  /** The variable each statement block assigned, by node id. */
  symbols: Record<string, string>
}

/** A run of emitted lines, with the block each one started at. */
type Fragment = {
  lines: string[]
  /** 0-based offsets into `lines`. */
  map: Array<{ offset: number; nodeId: string }>
}

/**
 * Hands out the variable names, by position in the program.
 *
 * Names come from where a block sits in the file rather than from its
 * internal id, and that is load-bearing: parsing the text and regenerating
 * it has to produce the same text, or the debounced round trip would
 * rewrite every name on every keystroke.
 */
function createNamer() {
  const assigned = new Map<string, string>()
  const counts = new Map<string, number>()

  return (node: BlockNode): string => {
    const existing = assigned.get(node.id)
    if (existing) return existing
    const segment = node.type.split('.').pop() ?? 'value'
    const base = segment.replace(/[^A-Za-z0-9_$]/g, '') || 'value'
    const next = (counts.get(base) ?? 0) + 1
    counts.set(base, next)
    const name = /^[0-9]/.test(base) ? `_${base}${next}` : `${base}${next}`
    assigned.set(node.id, name)
    return name
  }
}

/** A literal typed into a port, rendered as source. */
function literal(value: unknown): string {
  if (value === undefined || value === null) return 'undefined'
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : '0'
  if (typeof value === 'boolean') return String(value)
  return JSON.stringify(String(value))
}

/**
 * Events are emitted top to bottom, then left to right.
 *
 * Reading order on the canvas is the order in the file, so moving a block
 * changes the code the way the user expects rather than shuffling it.
 */
function eventOrder(a: BlockNode, b: BlockNode): number {
  return a.position.y - b.position.y || a.position.x - b.position.x || a.id.localeCompare(b.id)
}

/** Where a contiguous run of lines sits inside a larger run. */
function indexOfRun(haystack: string[], needle: string[]): number {
  if (!needle.length) return -1
  for (let start = 0; start + needle.length <= haystack.length; start += 1) {
    if (needle.every((line, offset) => haystack[start + offset] === line)) return start
  }
  return -1
}

export function generateProgram(
  graph: BlockGraph,
  registry: BlockRegistry,
  state: readonly AppVariable[] = [],
): GeneratedProgram {
  /** Guards the recursion against a cycle the checker has already reported. */
  const inFlight = new Set<string>()
  const symbolFor = createNamer()
  const symbols: Record<string, string> = {}

  /** The expression text for whatever feeds a port. */
  function expressionFor(nodeId: string, portId: string): string {
    const node = nodeById(graph, nodeId)
    const definition = node && registry.get(node.type)
    if (!node || !definition) return 'undefined'

    const link = incoming(graph, nodeId, portId)
    if (!link) {
      const port = findPort(definition, portId)
      return literal(node.values[portId] ?? port?.default)
    }

    const source = nodeById(graph, link.from.node)
    const sourceDefinition = source && registry.get(source.type)
    if (!source || !sourceDefinition) return 'undefined'

    // A block that occupies a step stores its result in a variable, so its
    // outputs are read by name. A pure expression is inlined where it is used.
    const isStatement = sourceDefinition.inputs.some((port) => port.type === 'Exec')
    if (isStatement) {
      const symbol = symbolFor(source)
      return sourceDefinition.read?.(symbol, link.from.port) ?? symbol
    }


    if (inFlight.has(source.id)) return 'undefined'
    inFlight.add(source.id)
    const text = sourceDefinition.generate({
      node: source,
      input: (port) => expressionFor(source.id, port),
      body: () => '',
      symbol: symbolFor(source),
      indent: '',
    })
    inFlight.delete(source.id)
    return text
  }

  /** The chain of steps leaving a port, as lines. */
  function chainFrom(nodeId: string, portId: string, indent: string): Fragment {
    const fragment: Fragment = { lines: [], map: [] }
    const visited = new Set<string>()
    let link = outgoing(graph, nodeId, portId)[0]

    while (link) {
      const node = nodeById(graph, link.to.node)
      const definition = node && registry.get(node.type)
      if (!node || !definition || visited.has(node.id)) break
      visited.add(node.id)

      // Bodies are generated first: the block wraps their text, and their
      // line attributions are folded in once the wrapper's shape is known.
      const bodies = new Map<string, Fragment>()
      const assigned = symbolFor(node)
      const text = definition.generate({
        node,
        input: (port) => expressionFor(node.id, port),
        body: (port) => {
          const body = chainFrom(node.id, port, `${indent}  `)
          bodies.set(port, body)
          return body.lines.join('\n')
        },
        symbol: assigned,
        indent,
      })

      if (text.includes(`const ${assigned} =`) || text.includes(`const ${assigned} of`)) {
        symbols[node.id] = assigned
      }

      if (text) {
        const statement = text.split('\n')
        const start = fragment.lines.length
        fragment.lines.push(indent + statement[0], ...statement.slice(1))
        fragment.map.push({ offset: start, nodeId: node.id })
        for (const body of bodies.values()) {
          const at = indexOfRun(statement, body.lines)
          if (at < 0) continue
          for (const entry of body.map) {
            fragment.map.push({ offset: start + at + entry.offset, nodeId: entry.nodeId })
          }
        }
      }

      link = outgoing(graph, node.id, 'exec')[0]
    }

    return fragment
  }

  const events = graph.nodes
    .filter((node) => registry.get(node.type)?.isEvent)
    .sort(eventOrder)

  const lines: string[] = [GENERATED_HEADER, '']
  const sourceMap: SourceMapEntry[] = []

  // The variables come first, so everything below can read them and a
  // person reading the file learns what the app remembers before they
  // learn what it does.
  const declaration = generateState(state)
  if (declaration) lines.push(declaration, '')

  if (!events.length) {
    lines.push('// No events yet. Add an “On App Start” or “On Click” block to begin.')
    return { code: `${lines.join('\n')}\n`, sourceMap, symbols }
  }

  for (const event of events) {
    const handler = event.type === 'event.click'
      ? `app.onClick(${expressionFor(event.id, 'target')}, async () => {`
      : 'app.onStart(async () => {'

    lines.push(handler)
    sourceMap.push({ line: lines.length, nodeId: event.id })

    const body = chainFrom(event.id, 'exec', '  ')
    const base = lines.length
    if (body.lines.length) {
      lines.push(...body.lines)
      for (const entry of body.map) sourceMap.push({ line: base + entry.offset + 1, nodeId: entry.nodeId })
    } else {
      lines.push('  // Nothing connected yet.')
    }

    lines.push('})')
    lines.push('')
  }

  sourceMap.sort((a, b) => a.line - b.line || a.nodeId.localeCompare(b.nodeId))
  return { code: `${lines.join('\n').replace(/\n+$/, '')}\n`, sourceMap, symbols }
}

/** The block a line of generated code came from, for error traceback. */
export function nodeAtLine(program: GeneratedProgram, line: number): string | undefined {
  let best: SourceMapEntry | undefined
  for (const entry of program.sourceMap) {
    if (entry.line <= line && (!best || entry.line > best.line)) best = entry
  }
  return best?.nodeId
}

/** Where a block's code starts, for revealing it from the canvas. */
export function lineOfNode(program: GeneratedProgram, nodeId: string): number | undefined {
  return program.sourceMap.find((entry) => entry.nodeId === nodeId)?.line
}
