/**
 * The visual database schema.
 *
 * Tables are drawn, not typed, and this turns them into the two artefacts a
 * running app actually needs: migrations, and typed fetchers the query blocks
 * line up with.
 *
 * Migrations are append-only. Renaming a column in the editor emits an
 * `ALTER TABLE` in the next migration rather than rewriting the first one,
 * because the first one has already run somewhere.
 */

export type ColumnType = 'text' | 'number' | 'boolean' | 'timestamp' | 'json'

export type Column = {
  name: string
  type: ColumnType
  required?: boolean
  unique?: boolean
}

export type Table = {
  name: string
  columns: Column[]
}

export type DataSchema = { tables: Table[] }

export const EMPTY_SCHEMA: DataSchema = { tables: [] }

const SQL_TYPE: Record<ColumnType, string> = {
  text: 'text',
  number: 'double precision',
  boolean: 'boolean',
  timestamp: 'timestamptz',
  json: 'jsonb',
}

const TS_TYPE: Record<ColumnType, string> = {
  text: 'string',
  number: 'number',
  boolean: 'boolean',
  timestamp: 'string',
  json: 'unknown',
}

/** A name safe to put in generated SQL and TypeScript. */
export function safeName(value: string, fallback: string): string {
  const cleaned = value.trim().toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '')
  return cleaned && !/^\d/.test(cleaned) ? cleaned : fallback
}

/** `users` becomes `User`, for the type the fetchers return. */
export function typeName(table: string): string {
  const singular = table.endsWith('s') ? table.slice(0, -1) : table
  return singular
    .split('_')
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('') || 'Row'
}

export type SchemaProblem = { table: string; message: string }

/** What is wrong with the schema, in the same voice as the graph checker. */
export function checkSchema(schema: DataSchema): SchemaProblem[] {
  const problems: SchemaProblem[] = []
  const seen = new Set<string>()

  for (const table of schema.tables) {
    if (seen.has(table.name)) {
      problems.push({ table: table.name, message: `Two tables are both called “${table.name}”.` })
    }
    seen.add(table.name)

    if (!table.columns.length) {
      problems.push({ table: table.name, message: `“${table.name}” has no columns yet.` })
    }

    const columns = new Set<string>()
    for (const column of table.columns) {
      if (columns.has(column.name)) {
        problems.push({ table: table.name, message: `“${table.name}” has two columns called “${column.name}”.` })
      }
      columns.add(column.name)
    }
  }

  return problems
}

/**
 * The first migration: everything, from nothing.
 *
 * Every table gets an `id` and a `created_at` without being asked. They are
 * needed by every application anyone has ever written, and leaving them to be
 * remembered is how a schema ends up with three different spellings of the
 * same column.
 */
export function createMigration(schema: DataSchema): string {
  if (!schema.tables.length) return '-- No tables yet.\n'

  const statements = schema.tables.map((table) => {
    const columns = [
      '  id bigserial primary key',
      ...table.columns.map((column) => {
        const parts = [`  ${column.name} ${SQL_TYPE[column.type]}`]
        if (column.required) parts.push('not null')
        if (column.unique) parts.push('unique')
        return parts.join(' ')
      }),
      '  created_at timestamptz not null default now()',
    ]
    return `create table if not exists ${table.name} (\n${columns.join(',\n')}\n);`
  })

  return `-- Generated by the Tungsten builder from the visual schema.\n\n${statements.join('\n\n')}\n`
}

/**
 * The migration that takes one schema to another.
 *
 * Only additive changes are emitted automatically. A dropped column is left
 * commented out: deleting data is a decision, not a consequence of editing a
 * diagram.
 */
export function diffMigration(previous: DataSchema, next: DataSchema): string {
  const lines: string[] = []
  const before = new Map(previous.tables.map((table) => [table.name, table]))

  for (const table of next.tables) {
    const old = before.get(table.name)
    if (!old) {
      lines.push(createMigration({ tables: [table] }).split('\n').slice(2).join('\n').trim())
      continue
    }
    const columns = new Set(old.columns.map((column) => column.name))
    for (const column of table.columns) {
      if (columns.has(column.name)) continue
      const constraint = column.required ? ' not null' : ''
      lines.push(`alter table ${table.name} add column ${column.name} ${SQL_TYPE[column.type]}${constraint};`)
    }
    const kept = new Set(table.columns.map((column) => column.name))
    for (const column of old.columns) {
      if (kept.has(column.name)) continue
      lines.push(`-- alter table ${table.name} drop column ${column.name}; -- uncomment to lose this data`)
    }
  }

  for (const table of previous.tables) {
    if (next.tables.some((candidate) => candidate.name === table.name)) continue
    lines.push(`-- drop table ${table.name}; -- uncomment to lose this table`)
  }

  if (!lines.length) return '-- Nothing changed.\n'
  return `-- Generated by the Tungsten builder from the visual schema.\n\n${lines.join('\n\n')}\n`
}

/** The typed row shapes and fetchers the query blocks call into. */
export function createFetchers(schema: DataSchema): string {
  if (!schema.tables.length) return '// No tables yet.\n'

  const blocks = schema.tables.map((table) => {
    const name = typeName(table.name)
    const fields = [
      '  id: number',
      ...table.columns.map((column) => (
        `  ${column.name}${column.required ? '' : '?'}: ${TS_TYPE[column.type]}`
      )),
      '  created_at: string',
    ].join('\n')

    return `export type ${name} = {\n${fields}\n}

export async function list${name}s(where?: Partial<${name}>): Promise<${name}[]> {
  return db.select('${table.name}', where) as Promise<${name}[]>
}

export async function create${name}(row: Omit<${name}, 'id' | 'created_at'>): Promise<${name}> {
  return db.insert('${table.name}', row) as Promise<${name}>
}`
  })

  return `// Generated by the Tungsten builder from the visual schema.
// The query blocks call these; edit the schema, not this file.

import { db } from './client'

${blocks.join('\n\n')}
`
}

/** The table names the query blocks should offer. */
export function tableNames(schema: DataSchema): string[] {
  return schema.tables.map((table) => table.name)
}
