/**
 * The shell server.
 *
 * The desktop build spawns a PTY in the Electron main process. This gives the
 * browser build the same thing: a Vite plugin that hosts real `node-pty`
 * processes behind a WebSocket, so the terminal in the browser is bash --
 * every command on the machine, job control, colour, `vim`, `top`, the lot --
 * rather than an emulation of ten commands.
 *
 * It exists only while a dev or preview server is running. It is never part
 * of a production bundle, `TUNGSTEN_SHELL=off` disables it, and it refuses
 * sockets whose Origin is not the page it is serving, because the thing on
 * the other end of this socket is a shell on your machine.
 */

import { createRequire } from 'node:module'
import { writeFileSync, mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import type { IncomingMessage, ServerResponse } from 'node:http'
import type { Duplex } from 'node:stream'

import { WebSocketServer, type WebSocket } from 'ws'
import type { Plugin, ViteDevServer, PreviewServer } from 'vite'

import {
  MAX_SESSIONS, PTY_SOCKET_PATH, SHELL_HTTP_PREFIX, parseClientMessage,
  type ServerMessage, type ShellInfo,
} from '../src/terminal/ptyProtocol.ts'

const require = createRequire(import.meta.url)

/** What one live shell looks like to this module. */
type Session = {
  id: string
  pty: { write: (data: string) => void; resize: (cols: number, rows: number) => void; kill: () => void; pid: number }
  socket: WebSocket
}

type PtyModule = {
  spawn: (file: string, args: string[], options: Record<string, unknown>) => {
    pid: number
    write: (data: string) => void
    resize: (cols: number, rows: number) => void
    kill: (signal?: string) => void
    onData: (listener: (data: string) => void) => void
    onExit: (listener: (event: { exitCode: number }) => void) => void
  }
}

/** Loaded lazily: a machine without a built node-pty should still serve the app. */
function loadPty(): { pty?: PtyModule; reason?: string } {
  try {
    return { pty: require('@homebridge/node-pty-prebuilt-multiarch') as PtyModule }
  } catch (error) {
    return { reason: `node-pty is not available: ${(error as Error).message}` }
  }
}

/**
 * Writes the rc file each shell starts from.
 *
 * It sources the user's own config first -- this is their shell, not ours --
 * and then adds the dictionary commands, so `man tar` answers from Tungsten
 * on a machine with no man pages installed, which is most containers.
 *
 * The endpoint is *not* written in here. The file is generated once and the
 * server's port is only truly known per session -- a preview server, a
 * second window, a restarted dev server all differ -- so the address arrives
 * in the environment of each shell and this file only supplies a fallback.
 */
function writeRcFile(): string {
  const directory = mkdtempSync(join(tmpdir(), 'tungsten-shell-'))
  const path = join(directory, 'rc.sh')
  writeFileSync(path, `# Generated by Tungsten. Sourced into each shell this IDE opens.
[ -f /etc/bash.bashrc ] && . /etc/bash.bashrc
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"

export TUNGSTEN_IDE=1
: "\${TUNGSTEN_SHELL_ENDPOINT:=http://127.0.0.1:5173${SHELL_HTTP_PREFIX}}"
export TUNGSTEN_SHELL_ENDPOINT

__tungsten_ask() {
  local route="$1" field="$2"; shift 2
  curl -sfG --data-urlencode "$field=$*" "$TUNGSTEN_SHELL_ENDPOINT/$route" \\
    || echo "tungsten: the dictionary is not reachable"
}

# Fall back to Tungsten's dictionary when the system has no page for it.
man() { command man "$@" 2>/dev/null || __tungsten_ask man name "\${@: -1}"; }
whatis() { command whatis "$@" 2>/dev/null || __tungsten_ask whatis name "$1"; }
apropos() { command apropos "$@" 2>/dev/null || __tungsten_ask apropos q "$*"; }
explain() { __tungsten_ask explain line "$*"; }
`)
  return path
}

/** ANSI, so a manual page in a real terminal reads like one. */
const BOLD = '\u001b[1m'
const DIM = '\u001b[2m'
const RED = '\u001b[31m'
const RESET = '\u001b[0m'

type DictionaryModules = {
  dictionary: { lookup: (name: string) => unknown; search: (query: string, options?: unknown) => unknown[]; suggest: (name: string) => string[]; entries: unknown[] }
  manPage: (entry: unknown) => Array<{ text: string; tone?: string }>
  explain: (line: string) => { sentences: string[]; warnings: string[] }
}

/** Renders the dictionary answers as terminal text. */
function dictionaryResponder(modules: DictionaryModules | null) {
  return (route: string, query: URLSearchParams): string => {
    if (!modules) return 'tungsten: the dictionary is only available from the dev server\n'
    const { dictionary, manPage, explain } = modules

    if (route === 'man' || route === 'whatis') {
      const name = (query.get('name') || '').trim()
      const entry = dictionary.lookup(name) as { name: string; summary: string; group: string } | undefined
      if (!entry) {
        const near = dictionary.suggest(name)
        return `No manual entry for ${name}\n${near.length ? `Did you mean: ${near.join(', ')}?\n` : ''}`
      }
      if (route === 'whatis') return `${entry.name} (${entry.group.toLowerCase()}) — ${entry.summary}\n`
      return `${manPage(entry).map((line) => {
        if (line.tone === 'heading') return `${BOLD}${line.text}${RESET}`
        if (line.tone === 'warning') return `${RED}${line.text}${RESET}`
        if (line.tone === 'muted') return `${DIM}${line.text}${RESET}`
        return line.text
      }).join('\n')}\n`
    }

    if (route === 'apropos') {
      const hits = dictionary.search(query.get('q') || '', { limit: 20 }) as Array<{ name: string; summary: string }>
      if (!hits.length) return `${query.get('q')}: nothing appropriate\n`
      return `${hits.map((entry) => `${entry.name.padEnd(18)}${entry.summary}`).join('\n')}\n`
    }

    if (route === 'explain') {
      const explanation = explain(query.get('line') || '')
      if (!explanation.sentences.length) return 'explain: nothing to read in that line\n'
      return `${[
        ...explanation.sentences,
        ...explanation.warnings.map((warning) => `${RED}! ${warning}${RESET}`),
      ].join('\n')}\n`
    }

    return `tungsten: unknown route ${route}\n`
  }
}

export type ShellPluginOptions = {
  /** Where new shells start. Defaults to the directory Vite was started in. */
  cwd?: string
}

export function tungstenShell(options: ShellPluginOptions = {}): Plugin {
  const sessions = new Map<string, Session>()
  const { pty, reason } = loadPty()
  const disabled = process.env.TUNGSTEN_SHELL === 'off'
  const shellPath = process.env.SHELL || '/bin/bash'
  const cwd = options.cwd || process.cwd()
  let rcFile: string | null = null
  /** The port the server is actually listening on, read when a shell starts. */
  let resolvePort: (() => number) | null = null
  let respond = dictionaryResponder(null)
  let loadDictionary: (() => Promise<void>) | null = null
  let loaded: Promise<void> | null = null
  let nextId = 1

  const info = (): ShellInfo => ({
    available: Boolean(pty) && !disabled,
    shell: shellPath,
    cwd,
    reason: disabled ? 'TUNGSTEN_SHELL=off' : reason,
    sessions: sessions.size,
    maxSessions: MAX_SESSIONS,
  })

  /**
   * Refuses a socket from a page we are not serving.
   *
   * Without this, any website open in the same browser could connect to the
   * dev server and run commands as you. The forwarded host is accepted as
   * well, because a hosted preview reaches the server through a proxy and the
   * page's origin is then the proxy's hostname, not ours.
   */
  const originAllowed = (request: IncomingMessage): boolean => {
    const origin = request.headers.origin
    if (!origin) return true
    const forwarded = request.headers['x-forwarded-host']
    const hosts = [request.headers.host, Array.isArray(forwarded) ? forwarded[0] : forwarded]
      .filter(Boolean)
      .flatMap((value) => String(value).split(',').map((host) => host.trim()))
    try {
      return hosts.includes(new URL(origin).host)
    } catch {
      return false
    }
  }

  const send = (socket: WebSocket, message: ServerMessage) => {
    if (socket.readyState === socket.OPEN) socket.send(JSON.stringify(message))
  }

  const startSession = (socket: WebSocket, cols: number, rows: number) => {
    if (!pty) return send(socket, { type: 'error', message: reason || 'No shell available.' })
    if (sessions.size >= MAX_SESSIONS) {
      return send(socket, { type: 'error', message: `Too many shells open (${MAX_SESSIONS}).` })
    }

    const id = `web-${nextId += 1}`
    const args = /bash$/.test(shellPath) && rcFile ? ['--rcfile', rcFile, '-i'] : ['-i']
    const child = pty.spawn(shellPath, args, {
      name: 'xterm-256color',
      cols,
      rows,
      cwd,
      env: {
        ...process.env,
        TERM: 'xterm-256color',
        COLORTERM: 'truecolor',
        TUNGSTEN_IDE: '1',
        TUNGSTEN_SHELL_ENDPOINT: `http://127.0.0.1:${resolvePort?.() ?? 5173}${SHELL_HTTP_PREFIX}`,
      },
    })

    const session: Session = { id, pty: child, socket }
    sessions.set(id, session)
    child.onData((data) => send(socket, { type: 'data', data }))
    child.onExit(({ exitCode }) => {
      sessions.delete(id)
      send(socket, { type: 'exit', code: exitCode })
      socket.close()
    })
    send(socket, { type: 'ready', id, shell: shellPath, cwd, pid: child.pid })
  }

  const handleSocket = (socket: WebSocket) => {
    let session: Session | undefined

    socket.on('message', (raw: unknown) => {
      const parsed = parseClientMessage(String(raw))
      if ('error' in parsed) return send(socket, { type: 'error', message: parsed.error })
      const message = parsed.message

      if (message.type === 'start') {
        if (session) return
        startSession(socket, message.cols, message.rows)
        session = [...sessions.values()].find((candidate) => candidate.socket === socket)
        return
      }
      if (!session) return
      if (message.type === 'input') session.pty.write(message.data)
      if (message.type === 'resize') session.pty.resize(message.cols, message.rows)
      if (message.type === 'kill') { session.pty.kill(); sessions.delete(session.id) }
    })

    socket.on('close', () => {
      // A closed tab must not leave a process behind.
      if (session) { try { session.pty.kill() } catch { /* already gone */ } sessions.delete(session.id) }
    })
  }

  /** The HTTP side: the health probe and the dictionary routes. */
  const middleware = (request: IncomingMessage, response: ServerResponse, next: () => void) => {
    const url = request.url || ''
    if (!url.startsWith(SHELL_HTTP_PREFIX)) return next()

    const parsed = new URL(url, 'http://localhost')
    const route = parsed.pathname.slice(SHELL_HTTP_PREFIX.length + 1)

    if (route === 'health') {
      response.setHeader('content-type', 'application/json')
      response.end(JSON.stringify(info()))
      return
    }

    // The dictionary is loaded through Vite on first use rather than at
    // startup, so a request cannot arrive before it is ready.
    loaded = loaded || (loadDictionary ? loadDictionary() : Promise.resolve())
    void loaded.then(() => {
      response.setHeader('content-type', 'text/plain; charset=utf-8')
      response.end(respond(route, parsed.searchParams))
    })
  }

  const attach = (server: ViteDevServer | PreviewServer, fallbackPort: number) => {
    if (!server.httpServer) return
    rcFile = writeRcFile()
    resolvePort = () => {
      const address = server.httpServer?.address()
      return typeof address === 'object' && address ? address.port : fallbackPort
    }

    const sockets = new WebSocketServer({ noServer: true })
    sockets.on('connection', handleSocket)

    server.httpServer.on('upgrade', (request: IncomingMessage, socket: Duplex, head: Buffer) => {
      if (!request.url?.startsWith(PTY_SOCKET_PATH)) return
      if (disabled || !pty || !originAllowed(request)) { socket.destroy(); return }
      sockets.handleUpgrade(request, socket, head, (ws) => sockets.emit('connection', ws, request))
    })

    server.httpServer.on('close', () => {
      for (const session of sessions.values()) { try { session.pty.kill() } catch { /* already gone */ } }
      sessions.clear()
      sockets.close()
    })
  }

  return {
    name: 'tungsten-shell',
    // Dev and preview only. A production bundle has no shell server in it,
    // which is the point: this is a development tool, not a deployed one.
    apply: 'serve',

    configureServer(server) {
      server.middlewares.use(middleware)
      // The dictionary is application source, so it is loaded through Vite
      // rather than duplicated here -- one set of entries, one explainer.
      loadDictionary = async () => {
        try {
          const index = await server.ssrLoadModule('/src/shell/commandDictionary.ts')
          const explainer = await server.ssrLoadModule('/src/shell/explainShell.ts')
          respond = dictionaryResponder({
            dictionary: index.shellDictionary,
            manPage: index.manPage,
            explain: (line: string) => explainer.explainCommandLine(line),
          })
        } catch (error) {
          server.config.logger.warn(`  tungsten-shell: the dictionary did not load (${(error as Error).message})`)
          respond = dictionaryResponder(null)
        }
      }

      return () => {
        const address = server.httpServer?.address()
        const port = typeof address === 'object' && address ? address.port : 5173
        attach(server, port)
        const state = info()
        server.config.logger.info(
          state.available
            ? `  \u001b[32m➜\u001b[0m  Shell:    real ${shellPath} over ${PTY_SOCKET_PATH} (same-origin only, TUNGSTEN_SHELL=off to disable)`
            : `  \u001b[33m➜\u001b[0m  Shell:    emulated — ${state.reason}`,
        )
      }
    },

    configurePreviewServer(server) {
      server.middlewares.use(middleware)
      return () => {
        const address = server.httpServer?.address()
        const port = typeof address === 'object' && address ? address.port : 4173
        attach(server, port)
      }
    },
  }
}

export default tungstenShell
