// Generated by scripts/build-graphene.mjs from src/theme/tokens.json.
// Do not edit by hand: re-run `npm run graphene` to refresh.
//
// Graphene is Tungsten's own design language and its default appearance. The
// imported VS Code themes in vscode-themes.generated.ts sit alongside it as
// alternatives; this is the one the product ships as.

import type { TungstenTheme } from './types'

export const grapheneTheme: TungstenTheme = {
  "id": "graphene-dark",
  "label": "Graphene Dark",
  "kind": "dark",
  "base": "vs-dark",
  "workbench": {
    "background": "#111311",
    "foreground": "#d5d9d5",
    "border": "#2b302b",
    "chrome": "#181b18",
    "chromeForeground": "#858c86",
    "activityBar": "#181b18",
    "activityBarForeground": "#c8f169",
    "activityBarInactive": "#5b615c",
    "activityBarBorder": "#2b302b",
    "badge": "#c8f169",
    "badgeForeground": "#10140c",
    "sidebar": "#171a17",
    "sidebarForeground": "#d5d9d5",
    "sidebarTitle": "#858c86",
    "sectionHeader": "#171a17",
    "statusBar": "#181b18",
    "statusBarForeground": "#858c86",
    "statusBarRemote": "#c8f169",
    "statusBarRemoteForeground": "#10140c",
    "tabActive": "#111311",
    "tabActiveForeground": "#f0f3ef",
    "tabInactive": "#181b18",
    "tabInactiveForeground": "#858c86",
    "tabBorder": "#2b302b",
    "tabActiveBorderTop": "#c8f169",
    "panel": "#111311",
    "panelBorder": "#2b302b",
    "listHover": "#232723",
    "listActive": "#2c3227",
    "listActiveForeground": "#f0f3ef",
    "listInactive": "#212421",
    "input": "#101210",
    "inputForeground": "#d5d9d5",
    "inputBorder": "#2b302b",
    "button": "#c8f169",
    "buttonForeground": "#10140c",
    "buttonHover": "#d9f78f",
    "widget": "#1d201d",
    "widgetBorder": "#383e38",
    "widgetShadow": "#000000cc",
    "focusBorder": "#c8f169",
    "accent": "#c8f169",
    "muted": "#858c86",
    "error": "#df756f",
    "warning": "#d4ae69",
    "info": "#68c3c8",
    "success": "#7cb342",
    "added": "#7cb342",
    "modified": "#d7ad5d",
    "deleted": "#d66059",
    "terminalBackground": "#111311",
    "terminalForeground": "#d5d9d5",
    "scrollbar": "#383e3880",
    "scrollbarHover": "#5b615ccc",
    "selection": "#c8f16938",
    "menuBackground": "#1d201d",
    "menuForeground": "#d5d9d5",
    "menuSelection": "#2c3227"
  },
  "terminal": {
    "background": "#111311",
    "foreground": "#d5d9d5",
    "cursor": "#c8f169",
    "selectionBackground": "#c8f16938",
    "black": "#212421",
    "red": "#df756f",
    "green": "#7cb342",
    "yellow": "#d4ae69",
    "blue": "#68c3c8",
    "magenta": "#b48add",
    "cyan": "#9fd4e0",
    "white": "#d5d9d5",
    "brightBlack": "#5b615c",
    "brightRed": "#e3958f",
    "brightGreen": "#c8f169",
    "brightYellow": "#dbbf8b",
    "brightBlue": "#8acfd2",
    "brightMagenta": "#c9a6e8",
    "brightCyan": "#b3dce4",
    "brightWhite": "#f0f3ef"
  },
  "editor": {
    "editor.background": "#111311",
    "editor.foreground": "#d5d9d5",
    "editorLineNumber.foreground": "#5b615c",
    "editorLineNumber.activeForeground": "#c8f169",
    "editorCursor.foreground": "#c8f169",
    "editor.selectionBackground": "#c8f16938",
    "editor.inactiveSelectionBackground": "#c8f1691a",
    "editor.selectionHighlightBackground": "#c8f16924",
    "editor.wordHighlightBackground": "#c8f1691f",
    "editor.wordHighlightStrongBackground": "#c8f1692e",
    "editor.findMatchBackground": "#c8f16952",
    "editor.findMatchHighlightBackground": "#c8f16929",
    "editor.lineHighlightBackground": "#191b19",
    "editor.lineHighlightBorder": "#00000000",
    "editorIndentGuide.background1": "#2b302b",
    "editorIndentGuide.activeBackground1": "#8fae4b",
    "editorWhitespace.foreground": "#383e38",
    "editorRuler.foreground": "#2b302b",
    "editorBracketMatch.background": "#c8f16929",
    "editorBracketMatch.border": "#5a6b39",
    "editorGutter.background": "#111311",
    "editorGutter.addedBackground": "#7cb342",
    "editorGutter.modifiedBackground": "#d7ad5d",
    "editorGutter.deletedBackground": "#d66059",
    "editorError.foreground": "#df756f",
    "editorWarning.foreground": "#d4ae69",
    "editorInfo.foreground": "#68c3c8",
    "editorHoverWidget.background": "#1d201d",
    "editorHoverWidget.border": "#383e38",
    "editorSuggestWidget.background": "#1d201d",
    "editorSuggestWidget.border": "#383e38",
    "editorSuggestWidget.foreground": "#d5d9d5",
    "editorSuggestWidget.selectedBackground": "#2c3227",
    "editorSuggestWidget.highlightForeground": "#c8f169",
    "editorWidget.background": "#1d201d",
    "editorWidget.border": "#383e38",
    "minimap.background": "#111311",
    "minimap.findMatchHighlight": "#c8f169",
    "scrollbarSlider.background": "#383e3880",
    "scrollbarSlider.hoverBackground": "#5b615cb3",
    "scrollbarSlider.activeBackground": "#5b615ce6",
    "editorOverviewRuler.border": "#00000000",
    "editorOverviewRuler.errorForeground": "#df756f",
    "editorOverviewRuler.warningForeground": "#d4ae69",
    "editorOverviewRuler.modifiedForeground": "#d7ad5d",
    "editorOverviewRuler.addedForeground": "#7cb342",
    "editorOverviewRuler.deletedForeground": "#d66059",
    "diffEditor.insertedTextBackground": "#7cb34224",
    "diffEditor.removedTextBackground": "#d6605924",
    "editorLink.activeForeground": "#c8f169",
    "editorCodeLens.foreground": "#5b615c"
  },
  "rules": [
    {
      "token": "",
      "foreground": "D5D9D5"
    },
    {
      "token": "comment",
      "foreground": "5F6B5F",
      "fontStyle": "italic"
    },
    {
      "token": "comment.doc",
      "foreground": "778177",
      "fontStyle": "italic"
    },
    {
      "token": "keyword",
      "foreground": "C8F169"
    },
    {
      "token": "keyword.control",
      "foreground": "C8F169"
    },
    {
      "token": "keyword.operator",
      "foreground": "98A398"
    },
    {
      "token": "storage",
      "foreground": "A8CF5C"
    },
    {
      "token": "storage.type",
      "foreground": "A8CF5C"
    },
    {
      "token": "string",
      "foreground": "A8D98A"
    },
    {
      "token": "string.escape",
      "foreground": "E0C179"
    },
    {
      "token": "regexp",
      "foreground": "D79B6F"
    },
    {
      "token": "number",
      "foreground": "E0C179"
    },
    {
      "token": "constant",
      "foreground": "E0C179"
    },
    {
      "token": "constant.language",
      "foreground": "E0C179"
    },
    {
      "token": "variable",
      "foreground": "D5D9D5"
    },
    {
      "token": "variable.parameter",
      "foreground": "C4CBC4"
    },
    {
      "token": "variable.predefined",
      "foreground": "E0C179"
    },
    {
      "token": "identifier",
      "foreground": "D5D9D5"
    },
    {
      "token": "entity.name.function",
      "foreground": "9FD4E0"
    },
    {
      "token": "support.function",
      "foreground": "9FD4E0"
    },
    {
      "token": "entity.name.type",
      "foreground": "8FD0A8"
    },
    {
      "token": "entity.name.class",
      "foreground": "8FD0A8"
    },
    {
      "token": "support.type",
      "foreground": "8FD0A8"
    },
    {
      "token": "support.class",
      "foreground": "8FD0A8"
    },
    {
      "token": "type",
      "foreground": "8FD0A8"
    },
    {
      "token": "type.identifier",
      "foreground": "8FD0A8"
    },
    {
      "token": "attribute.name",
      "foreground": "A8CF5C"
    },
    {
      "token": "attribute.value",
      "foreground": "A8D98A"
    },
    {
      "token": "tag",
      "foreground": "C8F169"
    },
    {
      "token": "metatag",
      "foreground": "C8F169"
    },
    {
      "token": "delimiter",
      "foreground": "8B948B"
    },
    {
      "token": "delimiter.bracket",
      "foreground": "8B948B"
    },
    {
      "token": "operator",
      "foreground": "98A398"
    },
    {
      "token": "namespace",
      "foreground": "8FD0A8"
    },
    {
      "token": "key",
      "foreground": "BCD9C4"
    },
    {
      "token": "string.key",
      "foreground": "BCD9C4"
    },
    {
      "token": "string.value",
      "foreground": "A8D98A"
    },
    {
      "token": "invalid",
      "foreground": "DF756F"
    },
    {
      "token": "predefined",
      "foreground": "E0C179"
    },
    {
      "token": "annotation",
      "foreground": "A8CF5C"
    }
  ],
  "semanticHighlighting": true
}
